### ISSUE TITLE
meal-reports | Задание №3

### ISSUE THREAD

**Issue by mashida** [Kyurasao/MealReports#10]
Создать класс Example003.

у него будут два параметра:
example_001: Example001
example_002: Example002

Сделать posterExample003, где ты отправишь такой объект.

И эндпойнт example003, Где ты его получишь.

**Comment by Kyurasao** [comment]
Результат должен быть такой?

![Image](https://github.com/Kyurasao/MealReports/assets/123263834/3b18e4f7-adbc-4cfe-9611-c850fb367c84)
