### ISSUE TITLE
Создать скрипт для работы с sqlite3

### ISSUE THREAD

**Issue by mashida** [Kyurasao/MealReports#13]
Создаёшь скрипт, который проверяет есть ли база с заданным именем. И если нет - создаёт, с колонками Имя и Время.

Создаёшь скрипт, который 

1. запрашивает у пользователья имя
2. записывает в базу время обращения
3. записывает в базу имя пользователя

**Comment by Kyurasao** [comment]
Мне нужен столбец `id`, который будет первичным ключом?

**Comment by mashida** [comment]
Точно!

ср, 9 авг. 2023 г., 14:15 Kyurasao ***@***.***>:

**Comment by Kyurasao** [comment]
То что я закомментировал в script.py не нужно писать?

**Comment by mashida** [comment]
Отличная работа.
