### ISSUE TITLE
Порядок в проекте

### ISSUE THREAD

**Issue by mashida** [Kyurasao/MealReports#15]
Мы дошли до того, что наш проект разросся.

Нужно создать папку 
- [x] db и положить в неё всё, что связано с базами данных.
- [x] webserver, и положить в неё сам сервер
- [x] poster, и полоижть в неё всё, что связано с нашими программами, тестирующими работу сервера.

На это 15 минут.

**Comment by Kyurasao** [comment]
Порядк навел

**Comment by mashida** [comment]
@Kyurasao  Как тебе теперешний вид проекта?

**Comment by Kyurasao** [comment]
Проще ориентироваться

**Comment by mashida** [comment]
`db.json` нам больше не нужен, можно удалять.
