### ISSUE TITLE
FastAPI-pydantic | Задание #1 

### ISSUE THREAD

**Issue by mashida** [Kyurasao/MealReports#8]
1. создать класс `Example001` на базе `BaseModel`
У которого есть всего один параметр `name: str`

2. сделать эндпойнт, который принимает объект этого класса

3. Сделать такой же файл `posterExample001.py` для отправки данных на эту ссылку, чтобы не было ошибки.

**Comment by Kyurasao** [comment]
Что такое эндпоинт?

**Comment by mashida** [comment]
это ссылка, на которую приходит GET или POST запрос. [Ответ в поиске](https://yandex.ru/search/?text=%D1%87%D1%82%D0%BE+%D1%82%D0%B0%D0%BA%D0%BE%D0%B5+%D1%8D%D0%BD%D0%B4%D0%BF%D0%BE%D0%B8%D0%BD%D1%82+api&lr=968)

**Comment by Kyurasao** [comment]
Принимает объект - это значит добавляет его в какую-то базу данных?

**Comment by mashida** [comment]
> Принимает объект - это значит добавляет его в какую-то базу данных?

Не обязательно.

**Comment by Kyurasao** [comment]
Нужно устранить ошибку, а сейчас обед

**Comment by mashida** [comment]
> Нужно устранить ошибку, а сейчас обед

🆗 А какая ошибка?

**Comment by Kyurasao** [comment]
Такая же как в прошлый раз

{"detail":[{"type":"missing","loc":["body","details"],"msg":"Field required","input":{"time":"WvOlmfqRdg","name":"Dish_2","food":"potato","amount":"1"},"url":"https://errors.pydantic.dev/2.1.2/v/missing"}]}

**Comment by mashida** [comment]
1. Я скопировал проект.
2. Создал вирутальное окружение
3. Запустил webserver.py
4. Запустил posterExample001.py

0 ошибок 
![image](https://github.com/Kyurasao/MealReports/assets/34740100/0207f40e-fc5d-44bd-aee2-6567d4154761)

Похоже, ты запускаешь posterExample нажимая зелёную кнопочку треугольник справа наверху, где у тебя настроен запуск poster,py, потому и ошибка та же.

**Comment by mashida** [comment]
Как передаётся объект Example001? Что он такое по сути?

![image](https://github.com/Kyurasao/MealReports/assets/34740100/7238d04e-2b09-47ae-818c-d5b714f99844)

**Comment by Kyurasao** [comment]
Я запускаю через хоткеи всегда. Но сейчас результат тот же, что и у тебя. Да, вижу. У меня строка должна быть. Исправляю

**Comment by Kyurasao** [comment]
Объект Example001 - это словарь с одним ключом `name` и его значением типа `str`

**Comment by mashida** [comment]
> Объект Example001 - это словарь с одним ключом `name` и его значением типа `str`

А какой словарь посылаешь ты?
![image](https://github.com/Kyurasao/MealReports/assets/34740100/3966f218-cf11-4031-a222-6b99482608c0)

**Comment by Kyurasao** [comment]
![Image](https://github.com/Kyurasao/MealReports/assets/123263834/c0287e96-6b88-4f4a-8e06-5785deee833c)

Теперь работает.
Я забыл, что имена "ящиков" не совпадают, а должны.
