### ISSUE TITLE
meal-reports | Задание №2

### ISSUE THREAD

**Issue by mashida** [Kyurasao/MealReports#9]
Теперь сделай класс `Example002`, где будет один параметер `list_of_names: List[str]`

если слово `List` будет подчёркнуто краснфм, нужно написать в самом верху в коде `from typing import List`

и написать `poster_example_002.py`, где будешь отправлять массив имён.

и напиши endpoint example002, где будешь принимать `item: Example002`

**Comment by Kyurasao** [comment]
Забыл удалить лишнее из posterExample001, а уже закрыл задачу. Также уже стал делать задание 2. Добавлю измененя в этой задаче. Такого лучше избегать?

**Comment by mashida** [comment]
Можно крепить коммиты к закрытым задачам.

Можно переоткрывать задачи.

пн, 7 авг. 2023 г., 16:20 Kyurasao ***@***.***>:

**Comment by mashida** [comment]
Хотя, я в posterExample002 не вижу как ты посылаешь списки еды.

**Comment by mashida** [comment]
> и написать `poster_example_002.py`, где будешь отправлять массив имён.
> 
> и напиши endpoint example002, где будешь принимать `item: Example002`

- [x] написать poster_example_002.py, **где будешь отправлять массив имён**.

- [x] и напиши endpoint `example002`, где будешь принимать item: Example002

**Comment by mashida** [comment]
Я нашёл изменения. Задание выполнено.
